name: PR Build

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  trigger-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Trigger Terraform Plan CodeBuild
        uses: aws-actions/aws-codebuild-action@v1
        with:
          project-name: 'TerraformPlan'
          region: 'your-aws-region'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
